env: "gymma"

env_args:
  key: null
  time_limit: 200
  state_repre_flag: "onehot"  # new
  pretrained_wrapper: null
  # LaRe (Language-based Reward) parameters
  use_lare_reward: false
  use_lare_training: false
  use_pretrained_model: false
  pretrained_model_name: "FT_QMIX_LARE_map_8x5_2agents_1.1M_map_8x5_3agents_1.1M_final.pth"
  use_separete_memory: false
  show_debug_logs: false
  use_finetuning: false
  finetuning_model_name: "QMIX_LARE_map_8x5_2agents_1.1M_final.pth"

test_greedy: True
test_nepisode: 100
test_interval: 50000
log_interval: 50000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 100050000